# Generated by Django 5.1.1 on 2024-10-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='map_link',
            field=models.URLField(blank=True),
        ),
    ]
