# Generated by Django 5.1.1 on 2024-10-06 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_review_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Contact',
        ),
        migrations.AlterField(
            model_name='info',
            name='doctors_count',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='info',
            name='map_link',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=18)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('problem_text', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
            ],
        ),
    ]
