# Generated by Django 5.1.1 on 2024-10-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_review_contact_alter_info_doctors_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='doctors_count',
            field=models.PositiveIntegerField(default=3, editable=False),
        ),
    ]
